# Generated by Django 5.1.7 on 2025-05-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('motif', models.CharField(max_length=255)),
                ('justification', models.TextField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttestationParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='formations/attestations/')),
                ('nom', models.CharField(max_length=255)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=20)),
                ('periode', models.CharField(max_length=50)),
                ('moyenne_generale', models.FloatField()),
                ('appreciation_generale', models.TextField()),
                ('decision', models.CharField(max_length=100)),
                ('rang', models.IntegerField()),
                ('date_edition', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CalendrierScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.CharField(choices=[('primaire', 'Primaire'), ('secondaire', 'Secondaire')], max_length=20)),
                ('filiere', models.CharField(blank=True, max_length=50, null=True)),
                ('effectif', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('annuel', 'Congé annuel'), ('maladie', 'Congé maladie'), ('maternite', 'Congé maternité'), ('paternite', 'Congé paternité'), ('exceptionnel', 'Congé exceptionnel')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('jours_ouvrables', models.IntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('motif', models.TextField(blank=True, null=True)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='conges/justificatifs/')),
                ('date_approbation', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('CTT', 'Contrat de Travail Temporaire'), ('CIR', "Contrat d'Insertion et de Réinsertion")], max_length=3)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire Brut')),
                ('devise', models.CharField(choices=[('$', 'Dollar Américain'), ('FC', 'Franc Congolais'), ('Shs', 'Shillings Ougandais')], default='$', max_length=3)),
                ('fonction', models.CharField(max_length=100)),
                ('heures_semaine', models.IntegerField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('resilie', 'Résilié')], default='actif', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('coefficient', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='conges/justificatifs/')),
                ('nom', models.CharField(max_length=255)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='contrats/')),
                ('nom', models.CharField(max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('contact_eleve', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_tuteur', models.CharField(max_length=20)),
                ('ecole_provenance', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='etablissement/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('culturel', 'Culturel'), ('sportif', 'Sportif'), ('academique', 'Académique'), ('autre', 'Autre')], max_length=20)),
                ('organisateur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('semestre', models.CharField(choices=[('premier', 'Premier Semestre'), ('second', 'Second Semestre'), ('troisieme', 'Troisième Semestre'), ('quatrieme', 'Quatrième Semestre')], max_length=20)),
                ('periode', models.CharField(choices=[('premier', 'Premier Période'), ('second', 'Seconde Période'), ('troisieme', 'Troisième Période'), ('quatrieme', 'Quatrième Période')], default='premier', max_length=20)),
                ('coefficient', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('type_formation', models.CharField(choices=[('pedagogique', 'Pédagogique'), ('technique', 'Technique'), ('administrative', 'Administrative'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('objectifs', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(max_length=200)),
                ('formateur', models.CharField(blank=True, max_length=200, null=True)),
                ('organisateur', models.CharField(blank=True, max_length=200, null=True)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('devise', models.CharField(choices=[('FC', 'Franc Congolais'), ('SHS', 'Shillings Ougandais'), ('EUR', 'Euro'), ('USD', 'Dollar Américain')], default='FC', max_length=3)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('realise', 'Réalisé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='HoraireCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Horaire de cours',
                'verbose_name_plural': 'Horaires des cours',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField()),
                ('pourcentage', models.IntegerField(blank=True, null=True)),
                ('dossier', models.TextField()),
                ('statut', models.CharField(choices=[('enregistre', 'Enregistré'), ('en_attente', 'En attente'), ('desinscrit', 'Désinscrit')], default='en_attente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('niveau', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evaluation', models.CharField(choices=[('examen', 'Examen'), ('devoir', 'Devoir'), ('controle', 'Contrôle')], max_length=20)),
                ('note_obtenue', models.FloatField()),
                ('maximum', models.FloatField(default=20.0)),
                ('date_evaluation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_participation', models.CharField(choices=[('inscrit', 'Inscrit'), ('present', 'Présent'), ('absent', 'Absent'), ('abandon', 'Abandon')], default='inscrit', max_length=20)),
                ('evaluation_formateur', models.TextField(blank=True, null=True)),
                ('evaluation_formation', models.TextField(blank=True, null=True)),
                ('attestation', models.FileField(blank=True, null=True, upload_to='formations/attestations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RapportAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('nombre_eleves_total', models.IntegerField()),
                ('nombre_eleves_nouveaux', models.IntegerField()),
                ('nombre_eleves_exclus', models.IntegerField()),
                ('nombre_enseignants', models.IntegerField()),
                ('nombre_personnel_administratif', models.IntegerField()),
                ('evenements_importants', models.TextField()),
                ('nombre_recompenses', models.IntegerField()),
                ('date_generation', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('observation', models.TextField(blank=True)),
                ('document_pdf', models.FileField(blank=True, null=True, upload_to='rapports_administratifs/')),
            ],
            options={
                'verbose_name': 'Rapport Administratif',
                'verbose_name_plural': 'Rapports Administratifs',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.IntegerField()),
                ('equipements', models.TextField()),
            ],
        ),
    ]
