# Generated by Django 5.1.7 on 2025-05-06 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrative', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='staff.enseignant'),
        ),
        migrations.AddField(
            model_name='classe',
            name='enseignant_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_dirigees', to='staff.enseignant'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrative.classe'),
        ),
        migrations.AddField(
            model_name='conge',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conge',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.enseignant'),
        ),
        migrations.AddField(
            model_name='conge',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.personneladministratif'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrats_enseignant', to='staff.enseignant'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrats_personnel', to='staff.personneladministratif'),
        ),
        migrations.AddField(
            model_name='cours',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='administrative.classe'),
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='staff.enseignant'),
        ),
        migrations.AddField(
            model_name='documentconge',
            name='conge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='administrative.conge'),
        ),
        migrations.AddField(
            model_name='documentcontrat',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='administrative.contrat'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='administrative.classe'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='tuteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='staff.tuteur'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='administrative.eleve'),
        ),
        migrations.AddField(
            model_name='absence',
            name='eleve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='administrative.eleve'),
        ),
        migrations.AddField(
            model_name='cours',
            name='emploi_du_temps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='administrative.emploidutemps'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='calendrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='administrative.calendrierscolaire'),
        ),
        migrations.AddField(
            model_name='examen',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative.classe'),
        ),
        migrations.AddField(
            model_name='examen',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative.cours'),
        ),
        migrations.AddField(
            model_name='horairecours',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='administrative.cours'),
        ),
        migrations.AddField(
            model_name='horairecours',
            name='emploi_du_temps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative.emploidutemps'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='classe_anterieure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_sortantes', to='administrative.classe'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='classe_montante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_entrantes', to='administrative.classe'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='administrative.eleve'),
        ),
        migrations.AddField(
            model_name='jourferie',
            name='calendrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours_feries', to='administrative.calendrierscolaire'),
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative.matiere'),
        ),
        migrations.AddField(
            model_name='note',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative.cours'),
        ),
        migrations.AddField(
            model_name='note',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='administrative.eleve'),
        ),
        migrations.AddField(
            model_name='participationformation',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.enseignant'),
        ),
        migrations.AddField(
            model_name='participationformation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative.formation'),
        ),
        migrations.AddField(
            model_name='participationformation',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.personneladministratif'),
        ),
        migrations.AddField(
            model_name='attestationparticipation',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='administrative.participationformation'),
        ),
        migrations.AddField(
            model_name='rapportadministratif',
            name='responsable_validation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cours',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative.salle'),
        ),
        migrations.AlterUniqueTogether(
            name='horairecours',
            unique_together={('cours', 'emploi_du_temps')},
        ),
        migrations.AlterUniqueTogether(
            name='participationformation',
            unique_together={('formation', 'enseignant', 'personnel')},
        ),
    ]
