# Generated by Django 5.1.7 on 2025-05-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportadministratif',
            name='date_generation',
            field=models.DateField(),
        ),
    ]
