# Generated by Django 5.1.7 on 2025-05-06 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0003_alter_rapportadministratif_date_generation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='rapports_administratifs/pdfs/')),
                ('nom', models.CharField(max_length=255)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_pdf', to='administrative.rapportadministratif')),
            ],
        ),
    ]
