# Generated by Django 5.1.7 on 2025-05-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0004_documentpdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentPDF',
        ),
    ]
