# Generated by Django 5.2.3 on 2025-06-28 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0005_delete_documentpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='rapports_administratifs/documents/')),
                ('nom', models.CharField(max_length=255)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='administrative.rapportadministratif')),
            ],
        ),
    ]
