# Generated by Django 5.2.3 on 2025-06-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0006_documentrapport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapportadministratif',
            name='document_pdf',
        ),
    ]
