# Generated by Django 5.2.3 on 2025-07-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0007_remove_rapportadministratif_document_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='devise',
            field=models.CharField(choices=[('FC', 'Franc Congolais'), ('SHS', 'Shillings Ougandais'), ('EUR', 'Euro'), ('USD', 'Dollar Américain')], default='$', max_length=3),
        ),
    ]
