# Generated by Django 5.1.7 on 2025-05-06 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrative', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('nationalite', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('situation_familiale', models.CharField(blank=True, max_length=50, null=True)),
                ('date_engagement', models.DateField()),
                ('anciennete', models.IntegerField(blank=True, null=True)),
                ('anciennete_unite', models.CharField(choices=[('semaines', 'Semaines'), ('mois', 'Mois'), ('annees', 'Années')], default='annees', max_length=10)),
                ('anciennete_grade', models.IntegerField(blank=True, null=True)),
                ('anciennete_grade_unite', models.CharField(choices=[('semaines', 'Semaines'), ('mois', 'Mois'), ('annees', 'Années')], default='annees', max_length=10)),
                ('grade_echeant', models.CharField(blank=True, max_length=50, null=True)),
                ('acte_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('diplome', models.CharField(max_length=100)),
                ('etat_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('cote', models.FloatField(blank=True, null=True)),
                ('lieu_affectation', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('titulaire', 'Titulaire'), ('vacataire', 'Vacataire'), ('stagiaire', 'Stagiaire'), ('contractuel', 'Contractuel')], max_length=20)),
                ('salaire_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('devise', models.CharField(choices=[('FC', 'Franc Congolais'), ('$', 'Dollar Américain'), ('Shs', 'Shillings Ougandais')], default='FC', max_length=3)),
                ('charge_horaire', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enseignants/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel/')),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('directeur', 'Directeur'), ('prefet', 'Préfet'), ('directeur_etudes', 'Directeur des Études'), ('disciplinaire', 'Disciplinaire'), ('secretaire', 'Secrétaire'), ('comptable', 'Comptable'), ('administratif', 'Administratif')], max_length=20)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('date_embauche', models.DateField()),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(choices=[('FC', 'Franc Congolais'), ('$', 'Dollar Américain'), ('Shs', 'Shillings Ougandais')], default='FC', max_length=3)),
                ('numero_secu', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° DE SÉCURITÉ SOCIALE')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('congé', 'Congé'), ('inactif', 'Inactif')], default='actif', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personnel Administratif',
                'verbose_name_plural': 'Personnel Administratif',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('contact_tuteur', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_depot', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('expire', 'Expiré')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.enseignant')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.personneladministratif')),
            ],
        ),
        migrations.CreateModel(
            name='FichierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents/')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='staff.documentpersonnel')),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sanction', models.CharField(choices=[('avertissement_oral', 'Avertissement oral'), ('avertissement_ecrit', 'Avertissement écrit'), ('blame', 'Blâme'), ('retenue_salaire', 'Retenue sur salaire'), ('suspension', 'Suspension'), ('licenciement', 'Licenciement'), ('autre', 'Autre')], max_length=20)),
                ('date_sanction', models.DateField()),
                ('date_effet', models.DateField()),
                ('motif', models.TextField()),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('duree_unite', models.CharField(choices=[('jours', 'Jour(s)'), ('mois', 'Mois'), ('annees', 'Année(s)')], default='jours', max_length=10)),
                ('montant_retenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('devise', models.CharField(choices=[('FC', 'Franc Congolais'), ('$', 'Dollar Américain'), ('Shs', 'Shillings Ougandais')], default='FC', max_length=3)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('donneur_sanction', models.CharField(choices=[('prefet_etudes', 'Préfet des études'), ('secretaire', 'Secrétaire'), ('promoteur', 'Promoteur'), ('directeur_etudes', 'Directeur des études')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('appliquee', 'Appliquée'), ('annulee', 'Annulée'), ('contestee', 'Contestée')], default='en_attente', max_length=20)),
                ('document_path', models.CharField(blank=True, max_length=255, null=True)),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.enseignant')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.personneladministratif')),
                ('validation_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_validees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FichierPreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='sanctions/preuves/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sanction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_preuves', to='staff.sanction')),
            ],
            options={
                'verbose_name': 'Fichier de preuve',
                'verbose_name_plural': 'Fichiers de preuves',
            },
        ),
        migrations.CreateModel(
            name='SpecialiteEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_competence', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('expert', 'Expert')], max_length=20)),
                ('annees_experience', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative.matiere')),
            ],
            options={
                'unique_together': {('enseignant', 'matiere')},
            },
        ),
    ]
